#!/usr/bin/env bash

get_abs_dirname() {
    echo "$(cd "$(dirname "$1")" && pwd)"
}

get_abs_filename() {
  echo "$(get_abs_dirname "$1")/$(basename "$1")"
}

if [[ -z "${GIT_MASK_WRAPPER}" || -z "${GIT_MASK_WRAPPER_DIR}" ]]; then
    export GIT_MASK_WRAPPER="$(get_abs_filename "${BASH_SOURCE[0]}")"
    export GIT_MASK_WRAPPER_DIR="$(dirname "${GIT_MASK_WRAPPER}")"
fi

if [[ -z "${GIT_MASK_REAL_GIT_PROGRAM}" ]]; then
    export GIT_MASK_REAL_GIT_PROGRAM="$(
        which -a git | while read -r exe
        do
            exe_dir="$(get_abs_dirname "$exe")"
            if [[ "$exe_dir" != "$GIT_MASK_WRAPPER_DIR" ]]; then
                echo "$(get_abs_filename "$exe")"
                break
            fi
        done
    )"
fi

if [[ ! -x "$GIT_MASK_REAL_GIT_PROGRAM" ]]; then
    echo "git-profile wrapper cannot find original git executable from \$PATH!" >&2
    exit 1
fi

(
    echo "$GIT_MASK_WRAPPER"
    echo "$GIT_MASK_REAL_GIT_PROGRAM"
)

